SELECT ENAME FROM EMP WHERE EMPNO IN (SELECT DISTINCT EMPNO FROM EMP WHERE SAL>ANY(SELECT SAL FROM EMP WHERE EMPNO IN(SELECT MGR FROM EMP)) AND EMPNO NOT IN(SELECT M.EMPNO FROM EMP E JOIN EMP M ON E.EMPNO=M.MGR WHERE E.SAL<M.SAL) AND MGR IS NOT NULL); //1

SELECT ENAME, SAL*12 AS ANNUAL_SALARY FROM EMP ORDER BY DEPTNO; //2

SELECT ENAME, SAL FROM (SELECT * FROM EMP ORDER BY SAL) WHERE ROWNUM<=5; //3

SELECT COUNT(E.ENAME) AS EMPLOYEE_COUNT FROM EMP E JOIN EMP M ON E.MGR=M.EMPNO WHERE E.SAL>M.SAL; //4

SELECT ENAME FROM EMP WHERE EMPNO IN(SELECT MGR FROM EMP) AND MGR NOT IN(SELECT EMPNO FROM EMP WHERE JOB='PRESIDENT'); //5

SELECT ENAME FROM EMP WHERE DEPTNO NOT IN(SELECT DEPTNO FROM DEPT); //6

SELECT ENAME FROM EMP WHERE (TO_DATE('31-DEC-89')-HIREDATE)/365 >= 20; //7

SELECT * FROM EMP WHERE MOD(SAL,200)=0; //8

SELECT * FROM EMP WHERE LENGTH(SAL)=3; //9

SELECT * FROM EMP WHERE TO_CHAR(HIREDATE,'MON')='DEC'; //10

SELECT CONCAT(UPPER(SUBSTR(ENAME,1,LENGTH(ENAME)/2)),LOWER(SUBSTR(ENAME,(LENGTH(ENAME)/2)+1,LENGTH(ENAME)))) FROM EMP; //11

SELECT * FROM EMP WHERE TO_NUMBER(TO_CHAR(HIREDATE, 'DD')) < 15; //12

SELECT * FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP); //13

SELECT * FROM (SELECT D.DEPTNAME, COUNT(E.DEPTNO) FROM EMP E JOIN DEPT D ON E.DEPTNO=D.DEPTNO GROUP BY D.DEPTNAME ORDER BY COUNT(E.DEPTNO) DESC) WHERE ROWNUM=1; //14

SELECT E1.EMPNO, E1.ENAME, E1.HIREDATE FROM EMP E1, EMP E2 WHERE E1.HIREDATE=E2.HIREDATE AND E1.ENAME<>E2.ENAME; //15

SELECT * FROM (SELECT ENAME, COUNT(ENAME) FROM(SELECT M.ENAME FROM EMP E, EMP M WHERE E.MGR=M.EMPNO) GROUP BY ENAME ORDER BY COUNT(ENAME) DESC) WHERE ROWNUM=1; //16


CREATE TABLE DEPT(DEPTNO NUMBER(4), DEPTNAME VARCHAR2(15), LOCATION VARCHAR2(20)) ADD CONSTRAINT PK PRIMARY KEY(DEPTNO);

INSERT INTO DEPT VALUES(10, 'IT', 'BANGALORE');
INSERT INTO DEPT VALUES(20, 'SALES', 'MUMBAI');
INSERT INTO DEPT VALUES(30, 'ACCOUNTING', 'KOLKATA');
INSERT INTO DEPT VALUES(40, 'MANAGEMENT', 'DELHI');

ALTER TABLE EMP ADD CONSTRAINT EMP_DEPT_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO);

SELECT E.EMPNO, E.DEPTNO, D.DEPTNAME, D.LOCATION FROM EMP E JOIN DEPT D ON E.DEPTNO=D.DEPTNO;
SELECT E.EMPNO, E.DEPTNO, D.DEPTNAME, D.LOCATION FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO;

SELECT D.DEPTNO, D.DEPTNAME, D.LOCATION FROM EMP E FULL JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE E.ENAME IS NULL;
SELECT * FROM DEPT WHERE DEPTNO NOT IN (SELECT DISTINCT DEPTNO FROM EMP);

SELECT JOB, COUNT(JOB) AS EMPLOYEES FROM EMP GROUP BY JOB;

SELECT JOB, COUNT(JOB) AS EMPLOYEES FROM EMP GROUP BY JOB HAVING COUNT(JOB)>=3;

SELECT JOB, COUNT(JOB) AS EMPLOYEES FROM EMP WHERE JOB IN ('CLERK','MANAGER') GROUP BY JOB HAVING COUNT(JOB)>=3;

SELECT ENAME, SAL, JOB FROM EMP WHERE EMP.SAL IN (SELECT MAX(SAL) AS MAX_SAL FROM EMP GROUP BY JOB);

SELECT ENAME, DEPTNO FROM EMP WHERE DEPTNO IN(SELECT DEPTNO FROM DEPT WHERE LOCATION='BANGALORE');
SELECT ENAME, LOCATION, EMP.DEPTNO FROM EMP JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO WHERE LOCATION='BANGALORE';

CREATE TABLE PRODUCT(PID NUMBER(4), PNAME VARCHAR2(20), PRICE NUMBER(5,2));
INSERT INTO PRODUCT VALUES(101, 'LED TV',500.45);
INSERT INTO PRODUCT VALUES(102, 'MOBILE',300.5);
INSERT INTO PRODUCT VALUES(103, 'LAPTOP',800.5);

CREATE TABLE SALES(PID NUMBER(4), ITEM_SOLD NUMBER(4));
INSERT INTO SALES VALUES(101, 5);
INSERT INTO SALES VALUES(102, 10);
INSERT INTO SALES VALUES(101, 15);

SELECT PNAME, (SELECT SUM(ITEM_SOLD)FROM SALES WHERE PID=P.PID) AS TOTAL_ITEM_SOLD FROM PRODUCT P;

CREATE TABLE SALESMAN AS (SELECT * FROM EMP WHERE JOB='SALESMAN');
INSERT INTO SALESMAN(SELECT * FROM EMP WHERE JOB='CLERK');